HSA.Homework/src/HSA.Homework.Web/Models/CurrencyRateInfo.cs
namespace HSA.Homework.Web.Models
{
	public class CurrencyRateInfo
	{
		public int CurrencyCodeA { get; set; }
		public int CurrencyCodeB { get; set; }
		public int Date { get; set; }
		public decimal RateSell { get; set; }
		public decimal RateBuy { get; set; }
		public decimal RateCross { get; set; }
	}
}

HSA.Homework/src/HSA.Homework.Web/Models/ErrorViewModel.cs
using System;

namespace HSA.Homework.Web.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

HSA.Homework/src/HSA.Homework.Web/Controllers/Api/TicketsApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HSA.Homework.Web;
using HSA.Homework.Web.Core.Services;

namespace HSA.Homework.Web.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class TicketsApiController : ControllerBase
    {
        private readonly ITicketsService _ticketsService;

        public TicketsApiController(ITicketsService ticketsService)
        {
            _ticketsService = ticketsService;
        }

        [HttpGet("get/postgres")]
        public async Task<ActionResult<IEnumerable<Ticket>>> GetTickets()
        {
            return (await _ticketsService.AllPostgres()).ToList();
        }

        [HttpGet("get/mongo")]
        public async Task<ActionResult<IEnumerable<Ticket>>> GetTicketsMongo()
        {
            return (await _ticketsService.AllMongo()).ToList();
        }

        [HttpPost("create/batch/mongo")]
        public async Task<ActionResult> CreateTicketsBatchMongo(IEnumerable<Ticket> tickets)
        {
            await _ticketsService.BatchCreateMongo(tickets.ToList());
            return Ok();
        }
    }
}

HSA.Homework/src/HSA.Homework.Web/Controllers/HomeController.cs
using HSA.Homework.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HSA.Homework.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

HSA.Homework/src/HSA.Homework.Web/Controllers/TicketsController.cs
using System.Threading.Tasks;
using HSA.Homework.Web.Core.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HSA.Homework.Web.Controllers
{
	public class TicketsController : Controller
    {
		private readonly ITicketsService _ticketsService;
		private readonly IBookingsService _bookingsService;

		public TicketsController(ITicketsService ticketsService, IBookingsService bookingsService)
        {
			_ticketsService = ticketsService;
			_bookingsService = bookingsService;
		}

        public async Task<IActionResult> Index()
        {
            var tickets = await _ticketsService.All(1000);
            return View(tickets);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _ticketsService.Get(id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        public IActionResult Create()
        {
            ViewData["BookRef"] = new SelectList(_bookingsService.All(), "BookRef", "BookRef");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TicketNo,BookRef,PassengerId,PassengerName,ContactData")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                await _ticketsService.Insert(ticket);
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookRef"] = new SelectList(_bookingsService.All(), "BookRef", "BookRef", ticket.BookRef);
            return View(ticket);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _ticketsService.Get(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["BookRef"] = new SelectList(_bookingsService.All(), "BookRef", "BookRef", ticket.BookRef);
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("TicketNo,BookRef,PassengerId,PassengerName,ContactData")] Ticket ticket)
        {
            if (id != ticket.TicketNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _ticketsService.Update(id, ticket);
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookRef"] = new SelectList(_bookingsService.All(), "BookRef", "BookRef", ticket.BookRef);
            return View(ticket);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _ticketsService.Get(id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _ticketsService.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        public  async Task<IActionResult> Sync()
        {
            var count = 1000;
            var time = await _ticketsService.SyncBenchmark(count);
            ViewData["SyncBenchmark"] = $"Synchronized {count} tickets. Time: {time} ms"; 
            return View();
        }
    }
}

HSA.Homework/src/HSA.Homework.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">HSA Homework</h1>
</div>

HSA.Homework/src/HSA.Homework.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HSA Homework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HSA Homework</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HSA.Homework.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/ConcurrentMongo.cshtml
@{
    ViewData["Title"] = "Concurrent Mongo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Mongo Find runned in 5 threads finished</h1>
</div>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/ConcurrentPostgres.cshtml
@{
    ViewData["Title"] = "Concurrent Postgres";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Postgres select runned in 5 threads finished</h1>
</div>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/Create.cshtml
@model HSA.Homework.Web.Ticket
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TicketNo" class="control-label"></label>
                <input asp-for="TicketNo" class="form-control" />
                <span asp-validation-for="TicketNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookRef" class="control-label"></label>
                <select asp-for="BookRef" class ="form-control" asp-items="ViewBag.BookRef"></select>
            </div>
            <div class="form-group">
                <label asp-for="PassengerId" class="control-label"></label>
                <input asp-for="PassengerId" class="form-control" />
                <span asp-validation-for="PassengerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassengerName" class="control-label"></label>
                <input asp-for="PassengerName" class="form-control" />
                <span asp-validation-for="PassengerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactData" class="control-label"></label>
                <input asp-for="ContactData" class="form-control" />
                <span asp-validation-for="ContactData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/Delete.cshtml
@model HSA.Homework.Web.Ticket
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassengerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassengerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassengerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassengerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookRefNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookRefNavigation.BookRef)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TicketNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/Details.cshtml
@model HSA.Homework.Web.Ticket
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassengerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassengerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassengerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassengerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookRefNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookRefNavigation.BookRef)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TicketNo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/Edit.cshtml
@model HSA.Homework.Web.Ticket

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TicketNo" />
            <div class="form-group">
                <label asp-for="BookRef" class="control-label"></label>
                <select asp-for="BookRef" class="form-control" asp-items="ViewBag.BookRef"></select>
                <span asp-validation-for="BookRef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassengerId" class="control-label"></label>
                <input asp-for="PassengerId" class="form-control" />
                <span asp-validation-for="PassengerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassengerName" class="control-label"></label>
                <input asp-for="PassengerName" class="form-control" />
                <span asp-validation-for="PassengerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactData" class="control-label"></label>
                <input asp-for="ContactData" class="form-control" />
                <span asp-validation-for="ContactData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/Index.cshtml
@model IEnumerable<HSA.Homework.Web.Ticket>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <p>
        <a asp-action="Sync">Sync to MongoDB</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PassengerId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PassengerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ContactData)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookRefNavigation)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PassengerId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PassengerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactData)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookRefNavigation.BookRef)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.TicketNo">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.TicketNo">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.TicketNo">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

HSA.Homework/src/HSA.Homework.Web/Views/Tickets/Sync.cshtml
@{
    ViewData["Title"] = "Sync";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["SyncBenchmark"]</h1>
</div>